import { dirname } from "path";
import { fileURLToPath } from "url";

import { FlatCompat } from "@eslint/eslintrc";
import prettier from "eslint-config-prettier";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      // Build output and generated files: not ours to lint.
      ".open-next/**",
      ".wrangler/**",
      "out/**",
      "build/**",
      "drizzle/**",
      "cloudflare-env.d.ts",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        {
          prefer: "type-imports",
          fixStyle: "inline-type-imports",
          // `typeof import("...")` in a type position is the only way to type
          // vitest's importOriginal helper.
          disallowTypeAnnotations: false,
        },
      ],
    },
  },
  // Generated by the better-auth CLI; kept as emitted apart from documented fixes.
  {
    files: ["db/auth-schema.ts"],
    rules: { "@typescript-eslint/consistent-type-imports": "off" },
  },
  prettier,
];

export default eslintConfig;
